### ISSUE TITLE
How do I connect to mainnet?

### ISSUE THREAD

**Issue by jedashford** [oxheadalpha/nft-tutorial#10]
New to Tezos, so I'm likely missing some basics. I see networks for sandbox and testnet. How do I connect to mainnet?

I have a feeling I need to run a node then connect to that, am I correct? Or is it as simple as the testnet and I just need a url and update `nft-tutorial/tznft.json`

**Comment by johnnyshankman** [comment]
This seems like such an obvious `Next Steps` section in the readme.

Like okay cool now I have no idea how to do this on mainnet, you've given me no tools to figure that out at all. This tutorial doesn't prepare you for mainnet in any way shape or form, so why even have it?

**Comment by emishur** [comment]
`tznft.json` now has `mainnet` configuration that can be selected with the `tznft set-network mainnet` command.
The mainnet configuration comes with no preconfigured account aliases though. You would need to add some funded account alias to make tznft work with the mainnet
