### ISSUE TITLE
tznft show-balance fails

### ISSUE THREAD

**Issue by dyske** [oxheadalpha/nft-tutorial#17]
`tznft show-balance` returns "invalid inspector storage state" because `lib/contracts.js` at line 133 checks `if (Array.isArray(storage))` and `storage` is not an array but:

```
storage {
  state: [
    { request: [Object], balance: [BigNumber] },
    { request: [Object], balance: [BigNumber] }
  ]
}
```

So, when I edited it to:

```
        if (Array.isArray(storage.state))
            printBalances(storage.state);
        else {
```

It worked.

**Comment by emishur** [comment]
Thank you for finding and reporting the issue. It is fixed now
