### ISSUE TITLE
nft origination error

### ISSUE THREAD

**Issue by geobiojon** [oxheadalpha/nft-tutorial#91]
Getting the following error trying to create a collection on ghostnet: 

nft origination error {
  "method": "GET",
  "url": "https://rpc.ghostnet.teztnets.xyz/chains/main/blocks/head/context/constants",
  "cause": {
    "message": "request to https://rpc.ghostnet.teztnets.xyz/chains/main/blocks/head/context/constants failed, reason: getaddrinfo ENOTFOUND rpc.ghostnet.teztnets.xyz",
    "type": "system",
    "errno": "ENOTFOUND",
    "code": "ENOTFOUND"
  },
  "name": "HttpRequestFailed",
  "message": "GET https://rpc.ghostnet.teztnets.xyz/chains/main/blocks/head/context/constants FetchError: request to https://rpc.ghostnet.teztnets.xyz/chains/main/blocks/head/context/constants failed, reason: getaddrinfo ENOTFOUND rpc.ghostnet.teztnets.xyz"
}
GET https://rpc.ghostnet.teztnets.xyz/chains/main/blocks/head/context/constants FetchError: request to https://rpc.ghostnet.teztnets.xyz/chains/main/blocks/head/context/constants failed, reason: getaddrinfo ENOTFOUND rpc.ghostnet.teztnets.xyz

**Comment by emishur** [comment]
Most likely Tezos  node you are trying to connect is temporary unavailable.
Try to connect to a different node.

**Comment by geobiojon** [comment]
How do I change nodes with tznft? Using the set-network command doesn't seem to allow swapping ghostnet nodes.

**Comment by emishur** [comment]
> How do I change nodes with tznft? Using the set-network command doesn't seem to allow swapping ghostnet nodes.

there is no CLI command, but you can manually edit generated `tznft.json` config file.
You need to either update `"providerUrl"` value for "testnet" json object or alternatively copy and rename `"test"` node and change `"providerUrl"`. 

`tznft` should be able to see new networks added to `tznft.json` file.

**Comment by geobiojon** [comment]
Worked great, thank you!
